apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intellmeet.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "intellmeet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  FRONTEND_URL: "{{ .Values.env.FRONTEND_URL }}"
  NODE_ENV: "{{ .Values.env.NODE_ENV }}"
