apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellmeet.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "intellmeet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: "{{ .Values.secret.JWT_SECRET }}"
  MONGO_URI: "{{ .Values.secret.MONGO_URI }}"
  SENTRY_DSN: "{{ .Values.secret.SENTRY_DSN }}"
